@userid = 5575af85-1b97-422a-90fe-d464004c8615

POST http://localhost:3000/
content-type: application/json

{
  "purchase": {
    "total": 10000,
    "products": [
      {
        "quantity": 1,
        "product": {
          "id": "2f983752-5bee-412c-b449-475740222811"
        }
      }
    ]
  },
  "buyerId": "d1e0b315-62d1-49b6-9d51-ff31ddc4fa47"
}

###

POST http://localhost:3000/user
content-type: application/json

{
  "name": "Gustavo Piovesan",
  "email": "gpossanii@outlook.com"
}

###

GET http://localhost:3000/user/{{userid}}

###

PATCH http://localhost:3000/user/{{userid}}
Content-Type: application/json

{
  "name": "Gustavo Possani",
  "email": "gpossanii@outlook.com"
}

###

DELETE http://localhost:3000/user/5575af85-1b97-422a-90fe-d464004c8615