include:
  - ../rabbitmq/docker-compose.yaml
  - ../postgres/docker-compose.yaml

services:
  stock-api:
    build: .
    container_name: stock-api
    ports:
      - 3001:3001
    volumes:
      - .:/home/root/app
    depends_on:
      - rabbitmq
      - postgres